In [2]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)
print("The shape of a is: ", a.shape)
print("The shape of b is: ", b.shape)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print("c = " + str(c))
print("Vectorized version: " + str(1000 * (toc - tic)) + "ms")

d = 0
tic = time.time()
for i in range(1000000):
    d += a[i] * b[i]
toc = time.time()
print("d = " + str(d))
print("For loop version: " + str(1000 * (toc - tic)) + "ms")

The shape of a is:  (1000000,)
The shape of b is:  (1000000,)
c = 250224.89753808078
Vectorized version: 0.7200241088867188ms
d = 250224.8975380848
For loop version: 129.9269199371338ms


In [8]:
import numpy as np

a = np.random.rand(3, 4)
print(a)
print(a.shape)

cal = a.sum(axis=0)
print(cal)
print(cal.shape)

percentage = 100*a/cal.reshape(1, 4)
print(percentage)
print(percentage.shape)

[[0.05323154 0.63845848 0.69399142 0.80744609]
 [0.33816993 0.66365896 0.21212788 0.37754269]
 [0.89870045 0.25645983 0.52088873 0.04625961]]
(3, 4)
[1.29010192 1.55857727 1.42700802 1.23124839]
(4,)
[[ 4.12615003 40.96418519 48.63262204 65.57946384]
 [26.21265233 42.58107501 14.86521953 30.66340578]
 [69.66119764 16.4547398  36.50215843  3.75713038]]
(3, 4)


In [2]:
import numpy as np
a = np.random.rand(3,4)
print(a)
b = np.random.rand(3,1)
print(b)
c = a+b
print(c)


[[0.76911987 0.5219871  0.36253961 0.28484139]
 [0.40136774 0.75151839 0.70819651 0.66155113]
 [0.49624868 0.6566764  0.43003568 0.7510444 ]]
[[0.30771826]
 [0.59191158]
 [0.47810217]]
[[1.07683813 0.82970536 0.67025787 0.59255965]
 [0.99327932 1.34342998 1.30010809 1.25346271]
 [0.97435085 1.13477857 0.90813785 1.22914657]]


In [ ]:
import numpy as np

a = np.random.rand(5,1)
print(a)
print(a.shape)

print(a.T)
print(a.T.shape)

print(np.dot(a,a.T))

[[0.79553682]
 [0.74455283]
 [0.15970496]
 [0.90666402]
 [0.12861525]]
(5, 1)
[[0.79553682 0.74455283 0.15970496 0.90666402 0.12861525]]
(1, 5)
[[0.63287883 0.5923192  0.12705117 0.72128461 0.10231817]
 [0.5923192  0.55435892 0.11890878 0.67505926 0.09576085]
 [0.12705117 0.11890878 0.02550567 0.14479874 0.02054049]
 [0.72128461 0.67505926 0.14479874 0.82203964 0.11661082]
 [0.10231817 0.09576085 0.02054049 0.11661082 0.01654188]]


In [4]:
import numpy as np

a = np.random.rand(5,2)

# assert(a.shape == (5,1))
# 如果a.shape≠(5,1)，则报错AssertionError: 

assert(a.shape == (5,2))

In [7]:
import numpy as np

a = np.random.randint(1,10,size=(3,2))
b = np.random.randint(1,10,size=(3,1))

print(a)
print(b)
print(a*b)
print(a*b.shape)

[[5 5]
 [6 1]
 [8 2]]
[[8]
 [9]
 [6]]
[[40 40]
 [54  9]
 [48 12]]
[[15  5]
 [18  1]
 [24  2]]


In [2]:
import numpy as np

r = -4 * np.random.rand()
print(r)

a = np.pow(10, r)
print(a)

-1.568224356526553
0.027025618599834357
